AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Queer Burners API SAM Template
Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 3
    CodeUri: lambdasrc/
    Tags:
      app: queerburners
    Layers:
      - !Ref NodeModulesLayer
    Environment:
      Variables:
        googleClientId: 1091094241484-ve5hbpa496m6d1k21m8r5ni16kvrkifi.apps.googleusercontent.com

Resources:
  CampsOptions:
    Type: AWS::Serverless::Function
    Properties:
      Description: "CORS pre-flight check"
      FunctionName: qb-camps-options
      Handler: multifunc.Options
      Events:
        CampsOptions:
          Type: Api
          Properties:
            Path: /camps
            Method: options

  CampsPost:
    Type: AWS::Serverless::Function
    Properties:
      Description: "Creates a new camp"
      FunctionName: qb-camps-post
      Handler: multifunc.campsPost
      Policies: AmazonDynamoDBFullAccess
      Events:
        CampsPost:
          Type: Api
          Properties:
            Path: /camps
            Method: post

  CampsGet:
    Type: AWS::Serverless::Function
    Properties:
      Description: "Gets a list of all camps"
      FunctionName: qb-camps-get
      Handler: multifunc.campsGet
      Policies: AmazonDynamoDBReadOnlyAccess
      Events:
        CampsGet:
          Type: Api
          Properties:
            Path: /camps
            Method: get

  CampsPictureUploadURLGet:
    Type: AWS::Serverless::Function
    Properties:
      Description: "Get a URL to upload a picture of a camp"
      FunctionName: qb-camps-picture-upload-url-get
      Handler: multifunc.campsPictureUploadURLGet
      Policies: AmazonS3FullAccess
      Events:
        CampsPictureUploadURLGet:
          Type: Api
          Properties:
            Path: /camps/pictureuploadurl/{format}
            Method: get

  CampsYearGet:
    Type: AWS::Serverless::Function
    Properties:
      Description: "Gets a list of camps for a single year"
      FunctionName: qb-camps-year-get
      Handler: multifunc.campsYearGet
      Policies: AmazonDynamoDBReadOnlyAccess
      Events:
        CampsYearGet:
          Type: Api
          Properties:
            Path: /camps/{year}
            Method: get

  CampsYearNameGet:
    Type: AWS::Serverless::Function
    Properties:
      Description: "Gets details of a single camp for a single year"
      FunctionName: qb-camps-year-name-get
      Handler: multifunc.campsYearNameGet
      Policies: AmazonDynamoDBReadOnlyAccess
      Events:
        CampsYearNameGet:
          Type: Api
          Properties:
            Path: /camps/{year}/{name}
            Method: get

  CampsYearNameDelete:
    Type: AWS::Serverless::Function
    Properties:
      Description: "Deletes a single camp"
      FunctionName: qb-camps-year-name-delete
      Handler: multifunc.campsYearNameDelete
      Policies: AmazonDynamoDBFullAccess
      Events:
        CampsYearNameDelete:
          Type: Api
          Properties:
            Path: /camps/{year}/{name}
            Method: delete

  IsAdmin:
    Type: AWS::Serverless::Function
    Properties:
      Description: "Checks if logged in user is an admin"
      FunctionName: qb-isadmin
      Handler: multifunc.isAdmin
      Policies: AmazonDynamoDBReadOnlyAccess
      Events:
        IsAdmin:
          Type: Api
          Properties:
            Path: /isadmin/{idToken}
            Method: get

  NodeModulesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: full set of function dependencies
      ContentUri: lambdalayer/
      CompatibleRuntimes:
        - nodejs12.x
      LicenseInfo: "Not applicable"
      RetentionPolicy: Retain
